[build]
    command = "npm run build"
    publish="/online-game/public"
    base = "/"
  functions = "netlify/functions" # Path to functions folder

[[redirects]]
    from = "/*"
    to = "/online-game/public/homepage.html"
    status = 200
    
[[[plugins]]]
  package = "@netlify/plugin-functions-install-core"